### ISSUE TITLE
PyVistaチュートリアル  |  「字形のプロット (ベクトルかPolyData) 」の表題の見直しを提案します

### ISSUE THREAD

**Issue by natsuwater** [pyvista/pyvista-tutorial-ja#22]
### Describe what maintenance you would like added.

I have a maintenance suggestion!

以下のページの表題についてのご提案です。

https://pyvista.github.io/pyvista-tutorial-ja/tutorial/04_filters/solutions/e_glyphs.html#sphx-glr-tutorial-04-filters-solutions-e-glyphs-py

このページの表題を修正するなら、「グリフ（矢印）によるベクトルの表示 」でしょうか。
少し意訳ぎみの訳が許容できるならば、という提案です。
「矢印のプロット (ベクトルかPolyData) 」の方が英語との対応は良いかもしれませんが、個人的にはここに PolyData が出てくる意味が理解できません。

もとの表題では、何を説明するページなのか、ちょっと理解できませんでした。しばらく考えて、Glyph の訳だ気づきました。この分野での定訳はないかもしれませんが、いくつかのソースをあたりました。

* 新英和大辞典では、「 (道案内の矢印のような, 言葉によらない情報伝達の)記号」という説明がされており、これに沿った訳が妥当と考えます。
* [ParaViewチュートリアル バージョン4.2](https://www.paraview.org/Wiki/images/a/a2/ParaViewTutorial42-jp.pdf)
 16ページで 「グリフ、すなわち単純な形状」 としています。これならわかりますが、チュートリアルの表題には使いにくいと思います。
* [ベクトル表示](https://www.rccm.co.jp/icem/pukiwiki/index.php?%E3%83%99%E3%82%AF%E3%83%88%E3%83%AB%E8%A1%A8%E7%A4%BA) (メッシュ Wiki)

また、正直なところ、 (Vectors or PolyData) と書いてあるものの、PolyData とのつながりがわかりません。
tutorial で紹介している例は、 mesh.glyph で 矢印を作って表示する例と DataSet.arrows で矢印を表示する例なので、端的には矢印の話をしていると理解しました。

お時間のあるとこにご検討いただければと思います。
よろしくお願いします。

**Comment by tkoyama010** [comment]
ご提案ありがとうございます。該当箇所は翻訳の際に苦慮した箇所です。この部分は意訳を許容したほうが伝わりやすそうですのでご提案の訳を反映させていただきます。

**Comment by tkoyama010** [comment]
[反映されました。](https://pyvista.github.io/pyvista-tutorial-ja/tutorial/04_filters/solutions/e_glyphs.html#sphx-glr-tutorial-04-filters-solutions-e-glyphs-py)
